### ISSUE TITLE
Enhancement No. 14 - Delete project mechanism

### ISSUE THREAD

**Issue by eieimon** [bluewave-labs/verifywise#506]

**Comment by gorkem-bwl** [comment]
@eieimon I think this is fixed on both the frontend and the backend right? If so, can you close it please? Thanks!

**Comment by eieimon** [comment]
@MuhammadKhalilzadeh - Hello Mo, may I know whether we are able to delete the project from dashboard or not? As far as I checked, I still get an error message about "Failed to delete project", reference has attached. According to your explanation, I understand that project has other dependencies such as assessments, to delete first before deleting the project itself, which we are now deleting those by using POSTMAN delete API. 

If those steps are required to perform the project delete, shouldn't we show something like a confirmation popup modal, indicating that "Everything related to this project will be deleted, Are you sure you want to delete this project?" message? 
What do you think? @gorkem-bwl 

<img width="1478" alt="Image" src="https://github.com/user-attachments/assets/5689b1e9-b374-4909-9d9b-e52e92048db8" />

**Comment by MuhammadKhalilzadeh** [comment]
Hi @eieimon 
1. The delete mechanism is recently implemented by @HarshP4585 
2. Yes. that's exactly what we need to do. Showing a popup indicating that everything related will be deleted.

**Comment by MuhammadKhalilzadeh** [comment]
@HarshP4585 
Is the server-side implementation complete for this feature?

**Comment by charurajput16** [comment]
@eieimon @MuhammadKhalilzadeh @gorkem-bwl - It is fixed now.
@HarshP4585 - Thank you so much!
